[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

auto_detect_solc = true
optimizer = true
optimizer-runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./out" },
]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
blast = "https://rpc.ankr.com/blast"
optimism = "https://optimism.llamarpc.com"
fantom = "https://rpc.ankr.com/fantom"
arbitrum = "https://rpc.ankr.com/arbitrum"
bsc = "https://rpc.ankr.com/bsc"
moonriver = "https://moonriver.public.blastapi.io"
gnosis = "https://rpc.ankr.com/gnosis"
Avalanche = "https://rpc.ankr.com/avalanche"
mantleSepolia = "https://rpc.ankr.com/mantle_sepolia"

[invariant]
runs = 20
depth = 10
fail_on_revert = false
dictionary_weight = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
